# Generated by Django 2.2.16 on 2022-06-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='pub_date',
        ),
    ]
