# Generated by Django 2.2.16 on 2022-06-09 19:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20220609_2028'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Уникальная подписка',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'author')},
        ),
    ]
