# Generated by Django 2.2.16 on 2022-06-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220609_2219'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(user)s подписан на %(author)s',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='Уникальная подписка'),
        ),
    ]
