# Generated by Django 2.2.16 on 2022-07-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220610_0014'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='Уникальная подписка',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='Unique_follow'),
        ),
    ]
